### PR TITLE
Make this a message listening service

### PR DESCRIPTION
**Pull request by soumyaray**
- Gemfile: add sinatra gem
- rubygems_crawler:
  - rename app to GemMiner
  - inherit from Sinatra::Base

### CODE REVIEW

**Comment by soumyaray** [comment]
Please leave a :+1: or similar icon if you are ok with these changes -- i'll merge it into master then.

**Comment by ChenLiZhan** [comment]
I think we need to care some coding style problems.

**Comment by soumyaray** [comment]
ok, i'll let @athoo fix things up a bit more on his branch before merging in then. (actually i might rebase on top of his... let's see).  Pinging, please issue a PR on your own branch when you get a bit more done :smile:.  My next change on this branch will be to add a route to accept SNS subscription.

**Comment by ChenLiZhan** [comment]
Okay! After you have set up the SNS service, I can start to work on my little ironworker. Do you think I need to open another repo for that?

**Comment by soumyaray** [comment]
@ChenLiZhan : yes, i think that should be another repo.  if i knew how to do submodules that might be a better option.  but for now, another repo.  actually, one day, i'd like to make more versions of this whole setup (crawler+worker+queue) for repos of other languages as well (like pypi).

**Comment by ChenLiZhan** [comment]
No prob. I'll do that later😄

**Comment by david23145** [comment]
:+1: merged it :p

**Pull request merged**
